MVCProjeKampi/Controllers/AdminPanel/ContactController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProjeKampi.Controllers
{
    public class ContactController : Controller
    {
        ContactManager contactManager = new ContactManager(new EfContactDal());
        MessageManager messageManager = new MessageManager(new EfMessageDal());
        ContactValidator validationRules = new ContactValidator();

        public ActionResult Index()
        {
            var contactValues = contactManager.List();
            return View(contactValues);
        }
        public ActionResult GetContactDetails(int id)
        {
            var contactValues = contactManager.GetByID(id);
            contactValues.MessageRead = true;
            contactManager.ContactUpdate(contactValues);
            return View(contactValues);
        }
        public PartialViewResult LeftMenuPartial()
        {
            string mail = (string)Session["AdminMail"];

            var contactCount = contactManager.List().Where(x => !x.MessageRead).Count();
            ViewBag.contactCount = contactCount;

            var inboxCount = messageManager.ListInbox(mail).Where(x => !x.MessageRead).Count();
            ViewBag.inboxCount = inboxCount;

            var sendboxCount = messageManager.ListSendbox(mail).Where(x => !x.MessageRead).Count();
            ViewBag.sendboxCount = sendboxCount;
            return PartialView();
        }
        public PartialViewResult NewMessageIcon()
        {
            return PartialView();
        }
    }
}

MVCProjeKampi/Controllers/WriterPanel/WriterMessageController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProjeKampi.Controllers.WriterPanel
{
    public class WriterMessageController : Controller
    {
        // GET: WriterMessage
        MessageManager messageManager = new MessageManager(new EfMessageDal());
        MessageValidator validationRules = new MessageValidator();

        ContactManager contactManager = new ContactManager(new EfContactDal());
        OtherValuesManager OtherValuesManager = new OtherValuesManager(new EfOtherValuesDal());

        public ActionResult Inbox()
        {
            string mail = (string)Session["WriterMail"];
            var messageList = messageManager.ListInbox(mail);
            return View(messageList);
        }
        public ActionResult Sendbox()
        {
            string mail = (string)Session["WriterMail"];
            var messageList = messageManager.ListSendbox(mail);
            return View(messageList);
        }

        public PartialViewResult LeftMenuPartial()
        {
            string mail = (string)Session["WriterMail"];

            var inboxCount = messageManager.ListInbox(mail).Where(x => !x.MessageRead).Count();
            ViewBag.inboxCount = inboxCount;

            return PartialView();
        }

        public PartialViewResult InboxPartial(int id)
        {
            var messageValues = messageManager.GetByID(id);
            return PartialView(messageValues);
        }

        public PartialViewResult SendboxPartial(int id)
        {
            var messageValues = messageManager.GetByID(id);
            return PartialView(messageValues);
        }

        public ActionResult GetMessageDetails(int id, string type)
        {
            var result = messageManager.Belong(id, (string)Session["WriterMail"]);
            if (result != null)
            {
                ViewBag.MessageType = type;
                var messageValues = messageManager.GetByID(id);
                messageValues.MessageRead = true;
                messageManager.MessageUpdate(messageValues);
                return View(messageValues);
            }
            else
            {
                return RedirectToAction("Page404", "ErrorPage");
            }
        }

        [HttpGet]
        public ActionResult NewMessage()
        {
            return View();
        }
        [HttpPost]
        public ActionResult NewMessage(Message message)
        {
            string fileName = OtherValuesManager.GetFileName();


            for (int i = 0; i < Request.Files.Count; i++)
            {
                if (Request.Files[i].FileName != "")
                {
                    string[] uzanti = Request.Files[i].FileName.ToString().Split('.');

                    Request.Files[i].SaveAs(Server.MapPath("~/Files/" + fileName + "." + uzanti[1]));
                    message.FileName = "/Files/" + fileName + "." + uzanti[1];
                }
            }


            ValidationResult result = validationRules.Validate(message);
            if (result.IsValid)
            {
                string writerMail = (string)Session["WriterMail"];
                message.MessageDate = DateTime.Now;
                message.MessageStatus = true;
                message.SenderMail = writerMail;
                messageManager.MessageAdd(message);
                return RedirectToAction("Sendbox");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
    }
}

MVCProjeKampi/Views/WriterMessage/GetMessageDetails.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "GetMessageDetails";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Gelen Mesaj Detayları</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("LeftMenuPartial", "WriterMessage")
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Mesajı Oku</h3>
                            <div class="card-tools">
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            @if (ViewBag.MessageType == "Inbox")
                            {
                                @Html.Action("InboxPartial", "WriterMessage")
                            }
                            else
                            {
                                @Html.Action("SendboxPartial", "WriterMessage")
                            }
                        </div>

                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
    </section>
</body>
</html>

MVCProjeKampi/Views/WriterMessage/Inbox.cshtml
@using EntityLayer.Concrete
@model List<Message>
@{
    ViewBag.Title = "Inbox";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesaj Sayfası</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            @Html.Action("LeftMenuPartial", "WriterMessage")
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Kişisel Gelen Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Mail Kutusunda Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                <div class="icheck-primary">
                                                    @if (!item.MessageRead)
                                                    {
                                                        @Html.Action("NewMessageIcon", "Contact")
                                                    }
                                                </div>
                                            </td>
                                            <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a></td>
                                            <td class="mailbox-name"><a href="/WriterMessage/GetMessageDetails/@item.MessageID/Inbox">@item.SenderMail</a></td>
                                            <td class="mailbox-subject">
                                                <b>@item.Subject</b> - @item.MessageContent.Substring(0, 3) ...
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date">@(((DateTime)item.MessageDate).ToString("dd-MMM-yyyy mm-HH"))</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

</body>
</html>

MVCProjeKampi/Views/WriterMessage/InboxPartial.cshtml
<div class="mailbox-read-info">
    <h5>@Model.Subject</h5>
    <br />
    <h6>
        Sender Mail: @Model.SenderMail
        <span class="mailbox-read-time float-right">@(((DateTime)Model.MessageDate).ToString("dd-MMM-yyyy mm-HH"))</span>
    </h6>
</div>
<!-- /.mailbox-read-info -->
<!-- /.mailbox-controls -->
<div class="mailbox-read-message">
    <p>@Html.Raw(@Model.MessageContent)</p>
    <img src="@Model.FileName" alt="Dosya" height="100" />
</div>
<!-- /.mailbox-read-message -->

MVCProjeKampi/Views/WriterMessage/LeftMenuPartial.cshtml
<div class="col-md-3">
    <a href="/WriterMessage/NewMessage/" class="btn btn-primary btn-block mb-3">Yeni Mesaj</a>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Seçenekler</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item active">
                    <a href="/WriterMessage/Inbox" class="nav-link">
                        <i class="fas fa-inbox"></i> Gelen Mesajlar
                        <span class="badge bg-primary float-right">@ViewBag.inboxCount</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/WriterMessage/Sendbox" class="nav-link">
                        <i class="far fa-envelope"></i> Gönderilen Mesajlar
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-file-alt"></i> Taslaklar
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fas fa-filter"></i> Spam
                        <span class="badge bg-warning float-right">65</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-trash-alt"></i> Çöp Kutusu
                    </a>
                </li>
            </ul>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Diğer</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-circle text-danger"></i>
                        Önemliler
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-circle text-warning"></i> Tanıtımlar
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="far fa-circle text-primary"></i>
                        Sosyal Medya
                    </a>
                </li>
            </ul>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>

MVCProjeKampi/Views/WriterMessage/NewMessage.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "NewMessage";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Yeni Mesaj Sayfası</h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("LeftMenuPartial", "WriterMessage")
                <!-- /.col -->
                <div class="col-md-9">
                    @using (Html.BeginForm("NewMessage", "WriterMessage", FormMethod.Post, new { enctype = "Multipart/form-data" }))
                    {
                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h3 class="card-title">Compose New Message</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.Label("Alıcı Mail:")
                                    @Html.TextBoxFor(x => x.RecieverMail, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.RecieverMail, "", new { @style = "color:red" })
                                </div>
                                <div class="form-group">
                                    @Html.Label("Konu:")
                                    @Html.TextBoxFor(x => x.Subject, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Subject, "", new { @style = "color:red" })
                                </div>
                                <div class="form-group">
                                    <textarea id="compose-textarea" name="MessageContent" class="form-control" style="height: 300px">
                                
                    </textarea>
                                </div>
                                <div class="form-group">
                                    <div class="btn btn-default btn-file">
                                        <i class="fas fa-paperclip"></i> Dosya Ekle
                                        <input type="file" name="arac" />
                                    </div>
                                    <p class="help-block">Max. 32MB</p>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <div class="float-right">
                                    <button type="button" class="btn btn-default"><i class="fas fa-pencil-alt"></i>Taslaklara Kaydet</button>
                                    <button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Gönder</button>
                                </div>
                                <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> Iptal Et</button>
                            </div>
                            <!-- /.card-footer -->
                        </div>
                    }
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->
    @*<script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>*@
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <!-- Summernote -->
    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/pages/dashboard3.js"></script>
    <!-- Page Script -->

</body>
</html>

MVCProjeKampi/Views/WriterMessage/Sendbox.cshtml
@using EntityLayer.Concrete
@model List<Message>
@{
    ViewBag.Title = "Sendbox";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesaj Sayfası</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            @Html.Action("LeftMenuPartial", "WriterMessage")
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Giden Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Mail Kutusunda Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                <div class="icheck-primary">
                                                    
                                                </div>
                                            </td>
                                            <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a></td>
                                            <td class="mailbox-name"><a href="/WriterMessage/GetMessageDetails/@item.MessageID/Sendbox">@item.RecieverMail</a></td>
                                            <td class="mailbox-subject">
                                                <b>@item.Subject</b> @item.MessageContent.Substring(0, 15)
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date">@(((DateTime)item.MessageDate).ToString("dd-MMM-yyyy mm-HH"))</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

</body>
</html>

MVCProjeKampi/Views/WriterMessage/SendboxPartial.cshtml
<div class="mailbox-read-info">
    <h5>@Model.Subject</h5>
    <br />
    <h6>
        Alıcı Mail: @Model.RecieverMail @Model.RecieverMail
        <span class="mailbox-read-time float-right">@(((DateTime)Model.MessageDate).ToString("dd-MMM-yyyy mm-HH"))</span>
    </h6>
</div>
<!-- /.mailbox-read-info -->
<!-- /.mailbox-controls -->
<div class="mailbox-read-message">
    <p>@Html.Raw(@Model.MessageContent)</p>
    <img src="@Model.FileName" alt="Dosya" height="100" />
</div>
<!-- /.mailbox-read-message -->