MVCProjeKampi/Controllers/AdminPanel/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProjeKampi.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminCategoryController : Controller
    {
        // GET: AdminCategory
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());

        public ActionResult Index()
        {
            var categoryValues = categoryManager.List().OrderByDescending(x => x.CategoryID).ToList();
            return View(categoryValues);
        }
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category category)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult Results = categoryValidator.Validate(category);
            if (Results.IsValid)
            {
                categoryManager.CategoryAdd(category);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var error in Results.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult DeleteCategory(int id)
        {
            var categoryValue = categoryManager.GetByID(id);
            categoryManager.DeleteCategory(categoryValue);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult UpdateCategory(int id)
        {
            var categoryValue = categoryManager.GetByID(id);
            return View(categoryValue);
        }
        [HttpPost]
        public ActionResult UpdateCategory(Category category)
        {
            categoryManager.CategoryUpdate(category);
            return RedirectToAction("Index");
        }
    }
}

MVCProjeKampi/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />

@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı");
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName, "", new { @style = "color:red" })
        <br /><br />
        @Html.Label("Kategori Açıklama");
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription, "", new { @style = "color:red" })
        <br /><br />
        <button class="btn btn-info">Ekle</button>
    </div>
}

MVCProjeKampi/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<form class="form form-group">
    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Ad</th>
            <th>Açıklama</th>
            <th>Durum</th>
            <th>Sil</th>
            <th>Güncelle</th>
            <th>Başlıklar</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <th>@item.CategoryID</th>
                <td>@item.CategoryName</td>
                <td>@item.CategoryDescription</td>
                <td>@item.CategoryStatus</td>
                <td><a href="/AdminCategory/DeleteCategory/@item.CategoryID" class="btn btn-danger">Sil</a></td>
                <td><a href="/AdminCategory/UpdateCategory/@item.CategoryID" class="btn btn-success">Güncelle</a></td>
                <td><a href="/Heading/Index/@item.CategoryID" class="btn btn-primary">Başlıklar</a></td>
            </tr>
        }
    </table>
    <a href="/AdminCategory/AddCategory" class="btn btn-info">Yeni Kategori Ekle</a>
</form>

MVCProjeKampi/Views/AdminCategory/UpdateCategory.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewBag.Title = "UpdateCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />

@using (Html.BeginForm("UpdateCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori ID")
        @Html.TextBoxFor(x => x.CategoryID, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryID, "", new { @style = "color:red" })
        <br /><br />
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName, "", new { @style = "color:red" })
        <br /><br />
        @Html.Label("Kategori Açıklama")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription, "", new { @style = "color:red" })
        <br /><br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}