MVCProjeKampi/Controllers/AdminPanel/ContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProjeKampi.Controllers
{
    public class ContentController : Controller
    {
        ContentManager contentManager = new ContentManager(new EfContentDal());

        public ActionResult Index()
        {
            var values = contentManager.List();
            return View(values);
        }
        public ActionResult SearchContent(string word)
        {
            if (!string.IsNullOrEmpty(word))
            {
                var values = contentManager.List(word);
                return View(values);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        public PartialViewResult SearchMenu()
        {
            return PartialView();
        }

        public ActionResult ContentByHeading(int id)
        {
            var contentValues = contentManager.ListByHeadingID(id);
            return View(contentValues);
        }
    }
}

MVCProjeKampi/Controllers/WriterPanel/WriterContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProjeKampi.Controllers.WriterPanel
{
    public class WriterContentController : Controller
    {
        // GET: WriterContent
        ContentManager contentManager = new ContentManager(new EfContentDal());
        public ActionResult Index()
        {
            int id = (int)Session["WriterID"];
            var values = contentManager.ListByWriterID(id);
            return View(values);
        }

        [HttpGet]
        public ActionResult AddContent(int id)
        {
            ViewBag.HeadingID = id;
            return View();
        }
        [HttpPost]
        public ActionResult AddContent(Content content)
        {
            content.ContentDate = DateTime.Now;
            content.WriterID = (int)Session["WriterID"];
            content.ContentStatus = true;
            contentManager.ContentAdd(content);
            return RedirectToAction("AllHeading","WriterHeading");
        }
        public ActionResult ContentByHeading(int id)
        {
            var contentValues = contentManager.ListByHeadingID(id);
            return View(contentValues);
        }
    }
}

MVCProjeKampi/Views/WriterContent/AddContent.cshtml
@model EntityLayer.Concrete.Content
@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

@using (Html.BeginForm("AddContent", "WriterContent", FormMethod.Post))
{
    <div class="form-group">
        <input type="hidden" name="HeadingID" value="@ViewBag.HeadingID" />
        <br />
        @Html.Label("Başlık Adı")
        @Html.TextAreaFor(x => x.ContentValue, 10, 30, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ContentValue, "", new { @style = "color:red" })
        <br />
        <button class="btn btn-info">Yazı Gönder</button>
    </div>
}

MVCProjeKampi/Views/WriterContent/ContentByHeading.cshtml
@using EntityLayer.Concrete
@model List<Content>

@{
    ViewBag.Title = "ContentByHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <br />
    @Html.Action("SearchMenu", "Content")
    <br />
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">
                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            @foreach (var item in Model)
                            {
                                <!-- timeline time label -->
                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd-MMM-yyyy"))</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Writer.WriterName @item.Writer.WriterSurName</a></h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                                <!-- END timeline item -->
                            }
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>

MVCProjeKampi/Views/WriterContent/Index.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">
                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            @foreach (var item in Model)
                            {
                                <!-- timeline time label -->
                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd-MMM-yyyy"))</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Heading.HeadingName</a></h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                                <!-- END timeline item -->
                            }
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>